version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks: 
      - TIG
    restart: always
    hostname: influxdb
    ports:
      - 8086:8086
    env_file: 
      - '.influxdb.env'
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    container_name: grafana
    restart: always
    networks: 
      - TIG
    ports:
      - 80:3000
    links:
      - influxdb:influxdb
    env_file: 
      - '.grafana.env'
    volumes:
      - grafana-data:/var/lib/grafana

  node-red:
    #image: nodered/node-red:latest
    container_name: nodered
    restart: always
    build: ./nodered
    environment:
     - TZ=Europe/Amsterdam
    ports:
      - "1880:1880" 
    volumes:
      - ./nodered/data:/data
    networks: 
      - TIG

networks: 
  TIG:

volumes:
  grafana-data: