{
 "title": "Smart collector",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Global Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Smart Collector Connectés",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "Weights",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "time", "operator": ">", "value": "now() - 1w" }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Evolution indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Poids",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "yaxes": [
    { "format": "massg" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "Weights",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batteries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "BatteriesState",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *4.2 / 4095" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per collectors Indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages per devices",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "device" ], "type": "tag" }
       ],
       "measurement": "Weights",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Weight Measured",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "device" ], "type": "tag" }
       ],
       "measurement": "Weights",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Battery State",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "device" ], "type": "tag" }
       ],
       "measurement": "BatteriesState",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " *4.2/ 4095" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Message",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "device" ], "type": "tag" }
       ],
       "measurement": "Weights",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}